---
- name: Load distribution based master setup
  include: "{{ ansible_distribution | lower }}-master-setup.yml"
  when: "master_group in group_names"
- name: Load distribution based slave setup
  include: "{{ ansible_distribution | lower }}-slave-setup.yml"
  when: "slave_group in group_names"

