# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vbguest.auto_update = false
  # config.vm.network "private_network", ip: "192.168.20.10"

  # config.vm.provider "virtualbox" do |vb|
  #   vb.cpus = 2
  #   vb.memory = "4096"
  # end

  config.vm.define "k8s_master" do |node|
    node.vm.network "private_network", ip: "192.168.20.10"
    node.vm.provider "virtualbox" do |vm|
      vm.cpus = 2
      vm.memory = 2048
    end
  end

  config.vm.define "k8s_slave" do |node|
    node.vm.network "private_network", ip: "192.168.20.11"
    node.vm.provider "virtualbox" do |vm|
      vm.cpus = 2
      vm.memory = 2048
    end
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
