# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vbguest.auto_update = false

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.auto_detect = false
    config.cache.enable :yum
  end

  $NODE_SCRIPT = <<-SHELL
      sudo echo "192.168.20.10 k8smaster" >> /etc/hosts
      sudo echo "192.168.20.11 k8sslave1" >> /etc/hosts
      sudo echo "192.168.20.12 k8sslave2" >> /etc/hosts
  SHELL

  config.vm.define "k8smaster" do |node|
    node.vm.network "private_network", ip: "192.168.20.10"
    node.vm.hostname = "k8smaster"
    node.vm.provider "virtualbox" do |vm|
      vm.cpus = 2
      vm.memory = 2048
    end
    node.vm.provision "shell", inline:  $NODE_SCRIPT
  end

  config.vm.define "k8sslave1" do |node|
    node.vm.network "private_network", ip: "192.168.20.11"
    node.vm.hostname = "k8sslave1"
    node.vm.provider "virtualbox" do |vm|
      vm.cpus = 2
      vm.memory = 2048
    end
    node.vm.provision "shell", inline:  $NODE_SCRIPT
  end

  config.vm.define "k8sslave2" do |node|
    node.vm.network "private_network", ip: "192.168.20.12"
    node.vm.hostname = "k8sslave2"
    node.vm.provider "virtualbox" do |vm|
      vm.cpus = 2
      vm.memory = 2048
    end
    node.vm.provision "shell", inline:  $NODE_SCRIPT
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
