---
- name: Create Kubernetes configuration folder
  file:
    path: '{{ kube_home }}'
    state: directory
    mode: 0755
- name: Setup kubernetes client config
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: '{{ kube_home }}/config'
# - name: Update configuration owner
#   shell: chown $(id -u):$(id -g) {{ kube_home }}/config
- name: Create kubernetes version hash
  raw: kubectl version | base64 | tr -d '\n'
  register: kube_version_hash
- name: setup kubernetes pod network
  command: "kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version={{ kube_version_hash.stdout }}"
- name: Store join command
  command: kubeadm token create --print-join-command
  register: k8s_master_join_command
