---
- name: Add Kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes official repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
- name: Install packages
  yum:
    name:
      - iproute-tc
      # - "kubeadm-{{ kubeadm_version }}"
      - "kubeadm"
- name: Ensure kubelet is started
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes
    state: started