all:
  children:
    k8s_dev:
      hosts:
        192.168.20.10:
      vars:
        ansible_user: vagrant
        ansible_ssh_private_key_file: ../vagrant/.vagrant/machines/default/virtualbox/private_key


