all:
  children:
    k8s_dev_master:
      hosts:
        192.168.20.10:
      vars:
        ansible_user: vagrant
        ansible_ssh_private_key_file: ../vagrant/.vagrant/machines/k8s_master/virtualbox/private_key
    k8s_dev_slave:
      hosts:
        192.168.20.11:
      vars:
        ansible_user: vagrant
        ansible_ssh_private_key_file: ../vagrant/.vagrant/machines/k8s_slave/virtualbox/private_key
    k8s_master:
      children:
        k8s_dev_master:
    k8s_slave:
      children:
        k8s_dev_slave:

