- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    yum:
      name: python2
      state: present
  - name: Gathering Facts
    setup:
  roles:
    - os_common
    - docker
    - { role: firewall_setup, master_group: k8s_master }
    - { role: kubernetes, master_group: k8s_master }
